server:
  port: 8088

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: training-service
          uri: http://localhost:8081/
          predicates:
            - Path=/training/**
        - id: dietplan-service
          uri: http://localhost:8080/
          predicates:
            - Path=/dietplan/**
        - id: schedule-service
          uri: http://localhost:8082/
          predicates:
            - Path=/schedule/**
        - id: user-service
          uri: http://localhost:8083/
          predicates:
            - Path=/user/**
  main:
    allow-bean-definition-overriding: true

