server:
  port:8080
spring:
  application:
    name: dietplan-service
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher








